version: "3.9"

services:
  db:
    image: "postgres:13"
    env_file:
      - .env.docker.db
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: "redis:6.2.1"
    ports:
      - 6379:6379

volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
